### ISSUE TITLE
Will Qt6 be supported in the future

### ISSUE THREAD

**Issue by zhaiyuhan** [wang-bin/QtAV#1294]
As we all know, QtAV is always the best video library under qt. But now is a minor repair, Qt6 release time is fast, QtAV will be updated in time?

**Comment by wang-bin** [comment]
Patches are welcome. You can try https://github.com/wang-bin/mdk-sdk, it's designed to support any app framework, include qt.

**Comment by cgilles** [comment]
Hi,

MDK is not so far a valid solution for OpenSource client application, as, it's not open source.

As long time developer of digiKam project, i ported from Qt multimedia/GStreamer SDK to QtAV, because QStreamer is a big puzzle and a poor solution to be easily portable everywhere. QtAV + ffmpeg is a suitable and powerful solution.

We will need a QtAV port to Qt6 as we have mostly ported all the 1.5 M lines of code to Qt6, and we won't to go back to Qt6Multimedia. We pass already a lots of time to change multimedia framework and start to use ffmpeg API for low level features for video supports. QtAv work fine and stable. So we want a Qt6 port soon.

Please revise this file and reopen it.

Best regards

Gilles Cauier

**Comment by wang-bin** [comment]
> Hi,
> 
> MDK is not so far a valid solution for OpenSource client application, as, it's not open source.
> 
> As long time developer of digiKam project, i ported from Qt multimedia/GStreamer SDK to QtAV, because QStreamer is a big puzzle and a poor solution to be easily portable everywhere. QtAV + ffmpeg is a suitable and powerful solution.
> 
> We will need a QtAV port to Qt6 as we have mostly ported all the 1.5 M lines of code to Qt6, and we won't to go back to Qt6Multimedia. We pass already a lots of time to change multimedia framework and start to use ffmpeg API for low level features for video supports. QtAv work fine and stable. So we want a Qt6 port soon.
> 
> Please revise this file and reopen it.
> 
> Best regards
> 
> Gilles Cauier 

It's easy to support qt6. Check out the latest code.

**Comment by cgilles** [comment]
Hi Wang,

Yes, i'm sure it's easy to port code, and i can contribute if time permit. After all i'm C++/Qt/Cmake developer since a while.

Do you mean that you already patch QtAV in this way and you needs client application feedback ?

Best

Gilles Caulier
