### ISSUE TITLE
Rendering VideoFrame

### ISSUE THREAD

**Issue by allbabel** [wang-bin/QtAV#367]
I am using QtAV::VideoDecoder to decode a H.264 AVC bitstream I am receiving over a tcp connection.  I am getting decoded frames and I can use either DXVA or FFmpeg in order to do this which is great.  Using VideoFrame::toImage() I can render the decoded frames using QPainter with no problem.  Obviously I don't want to use QPainter to render so I have been looking at using QQuickItemRenderer within a QML scene and calling VideoRenderer::receive() with my decoded VideoFrame.  If I use either frames with NV12 or YUV420P I just get a deep red area drawn in the area of the QQuickItemRenderer.  What is going wrong?

**Comment by wang-bin** [comment]
Are you writing your own renderer?
Most pixel formats are supported in QtAV using opengl, including nv12 and yuv420p. Currently QQuickItemRenderer is not used due to a strange crash. QuickFBORenderer is used in QML now. All opengl based renderers except QQuickItemRenderer in QtAV use the same class `OpenGLVideo`. You can read `QuickFBORenderer` and `OpenGLRendererBase` to know how to use `OpenGLVideo`.

**Comment by allbabel** [comment]
No, I am trying to use QQuickItemRenderer to render my video - I will take a look at QuickFBORenderer and let you know how I get on.  Thanks!
