### ISSUE TITLE
avutil is required, but compiler can not find it

### ISSUE THREAD

**Issue by Piusn** [wang-bin/QtAV#425]
I am getting "avutil is required, but compiler can not find it" when I try to build the solution on Qt creator. Kindly help

**Comment by dkomer** [comment]
When I had that problem, it was because I needed to update my path to include ffmpeg and portaudio...

This worked for me, hope it helps you- would be good if someone can confirm/correct that it's actually the best way and not a workaround

1) extract the prebuilt libs via the depends page: http://sourceforge.net/projects/qtav/files/depends/ (sort by date to get most recent, and make sure ffmpeg matches your target platform. note that ffmpeg is in its own folder actually, sorted by os)

After you've unzipped those somewhere, go to the PROJECTS pane in Qt Creator and select "details" drilldown. Then update the INCLUDE and LIB folder environment variable to include these paths. i.e. mine now look like:

INCLUDE:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;D:\GITHUB\DEPENDENCIES\ffmpeg\include;D:\GITHUB\DEPENDENCIES\portaudio\include;

LIB:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;D:\GITHUB\DEPENDENCIES\ffmpeg\lib;D:\GITHUB\DEPENDENCIES\portaudio\lib;

Once you've selected OK, the screen should show that build environment is using System Environment and *also* your strings for INCLUDE and LIB

After that, QtAV should build (note there's currently a problem with the debug version, so build in release mode, but that might even be fixed by the time you read this, hehe. Anyway you'll see a different error if that happens)

**Comment by dkomer** [comment]
(pay attention to the strings for include and lib, how they differ- i.e. ffmpeg\include and ffmpeg\lib)

**Comment by wang-bin** [comment]
debug build and deployment should be fixed in 15558fd . tested msbuild, nmake +vs2013 compiler.  Then run sdk_install.bat

**Comment by YealT** [comment]
2
