### ISSUE TITLE
DirectX video Renderer Fails Filter Operations

### ISSUE THREAD

**Issue by ShijinXincoz** [wang-bin/QtAV#453]
When trying to use Direct2D as video renderer the video Filter [to display messages] wont work.
Direct2D is used because some windows systems produces Black Screen on OpenGL video renderer.

Any help to produce Overlay Text on Video would be great..

**Comment by wang-bin** [comment]
If the filter is on a d2d renderer, you have to implement some painting functions (for example draw text) with direct2d. You can install the filter on the player instead of renderer then you message is rendered on the video frame.

OpenGL is always preferred.On what system opengl can not render correctly? What's your gpu?

Did you try qt5 + ANGLE?

**Comment by ShijinXincoz** [comment]
We dont have access to the client systems and so no idea about graphics configurations. The driver update is not a feasible solution.
If there is any starting point to write "D2DFilterContext", i would like to start.
will experiment with ANGLE project.

**Comment by ShijinXincoz** [comment]
We are using Qt5.4 and set video render as openGlWidget2 
To have ANGLE project with QtAV is it to change the video renderer or use a Qt version packed with ANGLE.
Also would like to know if any code change needed.

**Comment by wang-bin** [comment]
Qt5 can use ANGLE as it's opengl driver. Before Qt5.4, Qt is built with either OpenGL or ANGLE. Since 5.4, Qt supports to load ANGLE or OpenGL dynamically. Both ANGLE and OpenGL are supported in 1 binary. You can use environment var `set QT_OPENGL=angle` or `set QT_OPENGL=desktop` to set the opengl driver. Also you can set it in your c++ code

    qApp->setAttribute(Qt::AA_UseOpenGLES); //ANGLE
    qApp->setAttribute(Qt::AA_UseDesktopOpenGL); // desktop gl
    qApp->setAttribute(Qt::AA_UseSoftwareOpenGL);  // software

It seems that official download page does not provide dynamic gl package.  The package whose name does not contains `opengl` is built with ANGLE. To build dynamic gl support, you can add `-opengl dynamic` to configure options

**Comment by wang-bin** [comment]
of cause you can write `D2DFilterContext`. You have to use d2d APIs to render text and other basic things.
opengl has the best performance when rendering yuv images.

**Comment by wang-bin** [comment]
of cause you can write `D2DFilterContext`. You have to use d2d APIs to render text and other basic things.
opengl has the best performance when rendering yuv images.

**Comment by ShijinXincoz** [comment]
I've tried ANGLE version of Qt with visual studio 2013 and compiled the code without any change. But the same issue persists. What should I do next? The application goes black as soon as it starts. I used the OpenGLWidget renderer itself.

**Comment by wang-bin** [comment]
I find current code can not paint in ANGLE. It was fine before qtav 1.5.0.

**Comment by ShijinXincoz** [comment]
I could fix the filter issue by setting the filter to the player window instead of the renderer widget as you suggested. It workes fine with Direct2D renderer and all work fine now. Thanks for replying. :)

**Comment by wang-bin** [comment]
Do you mean install the filter on player? It should always work for software decoding.

**Comment by wang-bin** [comment]
If ANGLE is used and VBO is enabled(default), then qpainter filters on opengl video renderers can not work. I don't know why. As a workaround, VBO is disabled by default now if ANGLE is used. see 857347

**Comment by ShijinXincoz** [comment]
Ok now it's fine. Thanks :)
