### ISSUE TITLE
Subtitle not working in player.exe

### ISSUE THREAD

**Issue by ShijinXincoz** [wang-bin/QtAV#490]
When i playing .mkv file (It contains subtitle file) it don't showing the subtitles. In player it shows enabled. When i play the same in vlc player it shows the subtitles.

**Comment by wang-bin** [comment]
libass.dll is missing. I will update the depend package to include libass

**Comment by ShijinXincoz** [comment]
Ok. Thanks for reply.

**Comment by wang-bin** [comment]
I've uploaded libass.7z to sourceforge. Download and extract it. 

- Put include/ass to qt include dir
- Delete .qmake.conf in build dir
- Make sure contrib/capi/capi.h exists (run git submodule update --init)
- Run qmake again. You can see `checking libass....yes` from qmake output
- Build QtAV
- Put libass.dll to exe dir and it will be loaded at runtime.

In QMLPlayer you can select subtitle track in mkv when playing. I'm not sure ass subtitle can always work correctly because I only have 1 sample video tested.

**Comment by ShijinXincoz** [comment]
Thanks for the update. But after the update most of the time the application crush. So i can't properly test the out. Anyway i will check and tell u the details asap.

**Comment by ShijinXincoz** [comment]
Now the subtitle is working but only when we open and give the srt file manually. 
Thanks for the support.

**Comment by wang-bin** [comment]
If subtitle is in the same dir with video file and starts with the name of video, it will be loaded automatically
