### ISSUE TITLE
QtAv slow down after seeking for 3 sec

### ISSUE THREAD

**Issue by devlo** [wang-bin/QtAV#517]
I was testing qtav 1.8.0 vs2013 x64 on windows 10 x64. I've tried all three video decoders in qmlplayer and in widget one and in all of them with preview turned off. When i get from for example minute one to minute 10 i see slow down for around 3 sec like it would play 5 times slower, then it's starting playing next frames normal again. Tested on high bitrate 1080p h264 video file and on low bitrate 720p h264 file on i7-3770k/gtx 970.

**Comment by wang-bin** [comment]
It's an a/v sync issue for some videos in QtAV

**Comment by andyscratch** [comment]
The same happened to me. When I seek with the slider it slows for 3 secs and starts playing normal again. What actually is the paroblem. Also I have been able to develop a mediaplaylist for QtAV::AVPlayer just like QMediaPlayer has a QMediaPlaylist. But unlike QMediaPlayer which has a state() function I had to subclass AVPlayer and implement this myself as well as if I want the player to play from the playlist continuously either in sequential or random I have to provide a state variable such that anytime the stopped() signal is emitted the player will move to the next track in the playlist depending on playback mode implemented in the MediaPlaylist class. Also I would really love if you can show me how to query file meta data using the metadata variable in the Statistics class. Also is it possible to use two QtAV::AVPlayer so that I can compute file metadata in a different thread using the second player. Thank you.

**Comment by wang-bin** [comment]
@andyscratch  Why you need a subclass of AVPlayer? 

    AVPlayer.isPlaying() ? (AVPlayer.isPaused() ? QMediaPlayer.PausedState : QMediaPlayer.PlayingState) : QMediaPlayer.StoppedState

Neither QMediaPlayer nor AVPlayer is designed to be inheritable. You can make a patch if you want.

**Comment by andyscratch** [comment]
Are you sure? Cos I have inherited and is working. Did you declare the class with the final keyword?

**Comment by andyscratch** [comment]
I mean the player should emit a stateChanged() signal so that you need not connect to stopped() or started() signals.

**Comment by wang-bin** [comment]
@andyscratch Yes. `State` is better. I planed to add it before

**Comment by andyscratch** [comment]
ok. Because thats the main reason why I subclassed AVPlayer

**Comment by wang-bin** [comment]
`state` is added fe7974a10adf82758c607f4713d7cfaf024f9d0f

**Comment by wang-bin** [comment]
the latest code should be fine
