### ISSUE TITLE
QtAV performance

### ISSUE THREAD

**Issue by Lexerys** [wang-bin/QtAV#541]
Hello!

I'm using QtAV in my project to play h264 video in full hd resolution, it works - but I've found that playback starts to lag on low-end computers.
Also I've noticed that on that computers player.exe from your distributive works well.
But with some nuances:
  - player.exe from QtAV-Qt5.5.0-MinGW32-release-e60c890 show video without slowing;
  - player.exe from QtAV-VS2015x86-xp-latest and from QtAV1.8.0-VS2013x86.exe is very slow (fps falls to 30-50% from real speed).

I've compiled that project (player) from my QtAV sources, it slows too.

Using D2D renderer because there is often no opengl drivers on target computers (player.exe from QtAV-Qt5.5.0-MinGW32-release-e60c890 in D2D mode works well).
Also, if OpenGL is supported on target computer, D2D plays faster then OpenGL (~20%)

Using VS2015, qt 5.5.0, latest versions QtAV, ffmpeg - static builds.

Can you guid me to possible solutions please?

**Comment by wang-bin** [comment]
QtAV-VS2015x86-xp-latest is not the latest build. You can download the latest build from http://sourceforge.net/projects/qtav/files/ci/ Every time I push a commit, the ci system will build and upload there. Also, I only maintain master branch. So test the latest code please
You can try OpenGL ES if OpenGL is not supported. It's implemented by d3d. The performance should be better than d2d. Since Qt5.5, there are 2 ways to enable OpenGL ES
-  `qApp->setAttribute(Qt::AA_UseOpenGLES);`
-  qputenv("QT_OPENGL", "angle");
What's your target OS that has no OpenGL?
BTW, how do you build ffmpeg?

**Comment by Lexerys** [comment]
Problem solved - ffmpeg has been compiled with key "disable-yasm".
