### ISSUE TITLE
Running QtAV + QML on Windows Phone 8.1

### ISSUE THREAD

**Issue by sirl1on** [wang-bin/QtAV#543]
Hello,

I try to run a simple QtAV demo app on windows phone 8.1. Deployments for Android and iOS work flawlessly. I am not experienced in Qt & WP8.1 Development and Deployment so please bear with me.

* I successfully built ffmpeg for Windows Phone 8.1
* I successfully built QtAV for Windows Phone (ARM) and installed it via sdk_install.bat
* I generated a VS-Project using `qmake.exe C:\Folder\Project\Project.pro -r -spec winphone-arm-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" "CONFIG+=windeployqt" -r -tp vc`
* I copy all subfolders to Project\debug\MSIL to prevent deployment errors (see: https://bugreports.qt.io/browse/QTBUG-44335) 
* I open the vcxproj-file in Visual Studio 2015 and it builds successfully, except 1 Warning: `DEP0822: Error binding MDIL binary data. Error: 0x80070057` - I am translating the error message, I am not running an english OS.
* When I start the app on device it starts, but hangs at the Qt default splash screen.
* I get multiple `Cn::XH` Exceptions in KERNELBASE.DLL - these are not triggering a breakpoint by default so I am not sure if they should concern me
* Last output: `qrc:/main.qml:3 plugin cannot be loaded for module "QtAV": Cannot load library C:/Data/SharedData/PhoneTools/AppxLayouts/e185feaf-4ab5-4bc0-9220-2f466a749d9cVS.Debug_ARM.KST/QtAV/QmlAVd.dll: The specified module could not be found.` - QmlAVd.dll is in the QtAV subdirectory of the debug/MDIL folder so I suppose it will be copied to the device. Line 3 of main.qml is the import of QtAV. I haven't found a working way to check if the DLL is present on the device.

I would appreciate some help. I am out of ideas why the QtAV/QmlAVd.dll is not found.

**Comment by wang-bin** [comment]
I'm working on winrt/winphone recently. Please wait more a few weeks. Now I can run it on winrt x86, windows phone8.1 with the last code.
What's your Qt version? 5.6beta? I'm using 5.5.1 because there are some bugs in 5.6beta for winrt. 
I don't know the correct way to deploy additional files, for example ffmpeg dlls, QtAV1.dll. windeployqt is really stupid because it does not know what dlls the app depends on. For example QmlAV.dll (or QmlAVd.dll) requires QtAV1.dll, but QtAV1.dll will not be copied even if I wrote "QT += av". The modules are hardcoded in windeployqt. Then you will get the error `plugin cannot be loaded for module "QtAV": Cannot load `. For Qt5.5.1, you can read examples/QMLPlayer_sdk.pro. Add your dlls to `DEPLOYMENT`. The document says `DEPLOYMENT` is only for wince, but I find it also works for winrt in visualstudio, not qtcreator.
I never tried debug build. You can try release build.

`I copy all subfolders to Project\debug\MSIL to prevent deployment errors`
`I open the vcxproj-file in Visual Studio 2015 and it builds successfully, except 1 Warning:`
I don't know. No such errors for me. I haven't tried vs2015.

**Comment by sirl1on** [comment]
Thank you wang-bin,

i couldn't get DEPLOYMENT macro working (maybe a mistake on my part), I added QtAV1.dll and the FFmpeg libs to LIBS and now it works flawlessly! Thank you very much for your help!

**Comment by wang-bin** [comment]
can you build in vs for windows phone8.1?  I get an error

    >MakePri : error 0x80070057: Target C:\Program Files (x86)\Windows Phone Kits\8.1\\bin\x86\MrmEnvironmentExtDl.dll does not exist
    1>  uapp8.Windows -> resources.pri
    2>MakePri : error 0x80070057: Invalid path: C:\Program Files (x86)\Windows Phone Kits\8.1\\bin\x86\MrmEnvironmentExtDl.dll

**Comment by sirl1on** [comment]
looks like you are building for x86 (emulator?) arch which I haven't tried. I built QtAV for ARM devices and beside a little ffmpeg lib naming conflict it builds and works flawlessly. I used an external build script, which named the dlls not as expects (avcodec-16.dll instead of just avcodec.dll).

**Comment by wang-bin** [comment]
No. I build for arm. I don't know why it find in that folder. I repair vs2015 but it does not work. Now I copy the missing files from winphone 10 kit and it magically works. But i worry there will be some errors in the future. So can you give me the files in your environment? I need `C:\Program Files (x86)\Windows Phone Kits\8.1\Include\WinRT` and `C:\Program Files (x86)\Windows Phone Kits\8.1\bin\x86`
