### ISSUE TITLE
simpleplayer example broken

### ISSUE THREAD

**Issue by sklum** [wang-bin/QtAV#549]
Here's a minimally reproducing example.  The `VideoOutput` class seems to be the issue, as when I remove it, the widget will at least appear:
```
class Reviewer : public QWidget
{
    Q_OBJECT

protected:
    QGridLayout *layout;
    VideoOutput *video;
    AVPlayer *player;

public:
    explicit Reviewer(QWidget *parent = 0) :
        QWidget(parent),
        layout(new QGridLayout())
    {
        player = new AVPlayer(this);
        video = new VideoOutput(this);
        player->setRenderer(video);
        layout->addWidget(video->widget());
        setLayout(layout);
    }
};

int main(int argc, char *argv[])
{
    QtAV::Widgets::registerRenderers();
    QApplication app(argc, argv);
    Reviewer reviewer;
    reviewer.show();
    reviewer.resize(800, 600);

    return app.exec();
}
```

I get the runtime errors:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Reviewer(0x7fff599bc8e8), parent's thread is QThread(0x7f8bc9c42970), current thread is QThread(0x7f8bc9e75560)
QObject::connect: Cannot connect (null)::aboutToQuit() to QtAV::AVPlayer::aboutToQuitApp()
QObject::connect: Cannot connect (null)::aboutToQuit() to QtAV::VideoCapture::handleAppQuit()
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Reviewer(0x7fff599bc8e8), parent's thread is QThread(0x7f8bc9c42970), current thread is QThread(0x7f8bc9e75560)
Cannot create window: no screens available
```

**Comment by wang-bin** [comment]
which platform? what qt version?

**Comment by sklum** [comment]
Qt 5.5.1 on OSX 10.10.

**Comment by wang-bin** [comment]
I tested with the latest code. It runs fine. What qtav version do you use?

**Comment by mariolatronico** [comment]
Same problem here. 
Qt 5.5.1 on Windows, Mingw32 4.9.2 compiler.
Lastest QtAV stable (1.8.0)

**Comment by wang-bin** [comment]
Try the latest code

**Comment by mariolatronico** [comment]
I tried with the lastest code (QtAV-Qt5.5.0-MinGW32-release-86a7dc8, from today CI). 
I had the following problems on compiling and running the code.

1) OpenAL32.dll is not copied by the sdk_installer batch, I had to manually copy to my Qt bin directory
2) I had to rename the libQtAV1.a and libQtAVWidgets1.a to libQt5AV.a and libQt5AVWidgets.a, that is prefixing "5" before AV and removing "1" before the extension.

With these changes I could run the code in release mode only .

If I try the debug version, the linker complains because it couldn't find the debug versions ( libQt5Avd.a and libQt5Widgetsd.a).

Should I open a ticket requesting a debug version of the mingw32 libraries ? It's very handy because mingw32 is one of the default platform on Qt on Windows.

As a test I copied the release libraries to "debug" libraries (I simply renamed the copies appending a "d"). This way, the executable compiles in debug mode but it crashes with the following output :
```c++
Starting D:\QtAV\src\build-simpleplayer-Desktop_Qt_5_5_1_MinGW_32bit-Debug\debug\simpleplayer.exe...
VideoEncoder::Register(..., FFmpeg)
Singleton 1a2b85f8 created...
VideoDecoder::Register(..., FFmpeg)
Singleton 1a2b8660 created...
AudioOutputBackend::Register(..., null)
Singleton 1a2b86f8 created...
MediaIO::Register(..., QIODevice)
Singleton 1a2b8790 created...
MediaIO::Register(..., QFile)
ImageConverter::Register(..., FFmpeg)
Singleton 1a2b8a18 created...
AudioEncoder::Register(..., FFmpeg)
Singleton 1a2b8aa0 created...
AudioDecoder::Register(..., FFmpeg)
Singleton 1a2b8f20 created...
SubtitleProcessor::Register(..., FFmpeg)
Singleton 1a2b9198 created...
SubtitleProcessor::Register(..., LibASS)
VideoRenderer::Register(..., OpenGLWindow)
Singleton 1a2b9238 created...
VideoDecoder::Register(..., DXVA)
VideoDecoder::Register(..., CUDA)
AudioOutputBackend::Register(..., OpenAL)
AudioOutputBackend::Register(..., DirectSound)
AudioOutputBackend::Register(..., XAudio2)
AudioResampler::Register(..., FFmpeg)
Singleton 1a2b92c0 created...
VideoRenderer::Register(..., OpenGLWidget)
VideoRenderer::Register(..., QGLWidget2)
VideoRenderer::Register(..., Widget)
VideoRenderer::Register(..., GDI)
VideoRenderer::Register(..., Direct2D)
VideoRenderer::Register(..., GraphicsItem)
registerRenderers...........
registerRenderers...........
QObject: Cannot create children for a parent that is in a different thread.
(Parent is PlayerWindow(0x6cfe08), parent's thread is QThread(0x1a2ba8c0), current thread is QThread(0x1a2bb828)
AudioOutputBackend::next(1a2b92a8)
AudioOutputBackend::next(1a2b92ac)
AudioOutputBackend::next(1a2b92b0)
AudioOutputBackend::next(1a2b92b4)
AudioOutputBackend::id("XAudio2")
QObject::connect: Cannot connect (null)::aboutToQuit() to QtAV::AVPlayer::aboutToQuitApp()
QObject::connect: Cannot connect (null)::aboutToQuit() to QtAV::VideoCapture::handleAppQuit()
Unknown id QObject: Cannot create children for a parent that is in a different thread.
(Parent is PlayerWindow(0x6cfe08), parent's thread is QThread(0x1a2ba8c0), current thread is QThread(0x1a2bb828)
next id: 1613206256, name: OpenGLWindow
QPixmap: Must construct a QGuiApplication before a QPixmap
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
DestroySingleton...
D:\QtAV\src\build-simpleplayer-Desktop_Qt_5_5_1_MinGW_32bit-Debug\debug\simpleplayer.exe exited with code 3
```

**Comment by wang-bin** [comment]
The ci system for windows is too slow. So I didn't add mingw debug build. I can add one.

**Comment by wang-bin** [comment]
@mariolatronico mingw debug is added

**Comment by mariolatronico** [comment]
Thank you very much, it will be very useful !

Mario

**Comment by wang-bin** [comment]
Can't reproduce with the latest code

**Comment by fomin-stas** [comment]
@wang-bin Hi, where i can take libQt5Widgetsd.a and libQt5Avd.a?

**Comment by Dmi3Dev** [comment]
Hi, I'm getting same error when trying to run debug compiled simpleplayer example. 
`QObject: Cannot create children for a parent that is in a different thread. 
(Parent is MainWindow(0x7bfdc0), parent's thread is QThread(0x2007f690), current thread is QThread(0x2007fab0)
etc.`
Release works fine.

I'm on Win10, MSYS2 mingw64, gcc version 5.4.0 and Qt 5.6.1
I've compiled QtAV yesterday (Oct 12, 2016) from the latest git clone. Building QtAV went without any issues.

I do have QtAV.dll and QtAVd.dll and same for QtAVWidgets in in bin. and I made sure to use libQt5AVd.a for debug and libQt5AV.a for release and same for QtAVWidgets.

I also know that threading works fine in debug, because I have it in my other project.
Maybe you could give me a hint, what am I missing there to make QtAV work in debug? Do I have to double check for other dependent files to be in proper place?

Thanks.

**Comment by wang-bin** [comment]
@Dmi3Dev  I tested qt5.6.1 mingw32 debug from official installer and everything works. I don't have msys2 qt environment. Can you try official installer?

**Comment by wang-bin** [comment]
@fomin-stas you have to copy libQtAVd1.a and rename it

**Comment by Dmi3Dev** [comment]
Thanks for response. Unfortunately official binaries are only for 32 bit mingw and my end project need to be 64 bit. 
At the moment, while I'm learning your awesome library on Windows side, I'm compiling in release with debug info, that should, hopefully help for now.
Btw, even though Qt-project don't provide binaries for 64 bit, for those who needs that, they are recommend using MSYS2 version, or build it on top of it: https://wiki.qt.io/MinGW-64-bit
I mostly work on Linux side, so I should be ok doing debug there (haven't tried your library there yet, but will post here if I get same problem). 
I know, you are probably super busy, but If you ever get time to support MSYS2 by building package for it, you would make many cross platform developers very happy. Also I want to say: awesome job on the library!
