### ISSUE TITLE
When I called the function(that VideoFrame::toImage) the vaapi options doesn't work.

### ISSUE THREAD

**Issue by sulei-id** [wang-bin/QtAV#819]
Dear wang-bin:

I want to make a project for hw-decoding the rtsp-camera with libqtav on the ubuntu 14.04.

 I run the sample(/test/decoder) as `./test -f rtsp://admin:admin12345@172.16.1.248/h264/ch1/main/av_stream -vd vaapi`. It worked well, and the CPU load is only 3%-4%.

But when I added the code` frame.toImage()` after `dec->decode(pkt)` , the CPU load is up to 70%.

Then I did another test, excute the cmd `./test -f rtsp://admin:admin12345@172.16.1.248/h264/ch1/main/av_stream -vd ffmpeg`. And the CPU load is 70% too.

Why?

The hwdecode seems to  be invalid as long as I call the ` frame.toImage()`, the cpu load is no different between `vaapi` and `ffmpeg`.

Can you answer me, thanks.

**Comment by wang-bin** [comment]
Because toImage() must copy whole frame data from gpu to host memory, which is very slow. There is no better solution. If the decoded format is not rgb, then the frame will be converted to rgb by cpu. Converting can be optimized by using vaapi, but it's not supported now. You can check the cpu load of copying frame by using `frame.to(frame.format())` instead of `frame.toImage()`. If the difference is small compared to `toImage()`, then nothing can be improved.

**Comment by sulei-id** [comment]
@wang-bin Thanks very much, I have try your proposal, nothing can be improved.
